# Generated by Django 4.1.2 on 2023-02-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_json', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduino',
            name='permiso',
            field=models.BooleanField(default=False),
        ),
    ]
